/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Name = string;
export type Type = string | null;
export type Additionaltype = string | null;
export type Createdby = string;
export type Description = string;
export type Datecreated = string;
export type Associatedpublication = string | null;
export type Useddataset = IdentifierValue[] | null;
export type Id1 = string;
export type Generated = IdentifierValue[] | null;
export type Ispartof = IdentifierValue[] | null;

export interface Annotation {
  "@id": Id;
  name: Name;
  "@type"?: Type;
  additionalType?: Additionaltype;
  createdBy: Createdby;
  description: Description;
  dateCreated: Datecreated;
  associatedPublication?: Associatedpublication;
  usedDataset?: Useddataset;
  generated?: Generated;
  isPartOf?: Ispartof;
  [k: string]: unknown;
}
export interface IdentifierValue {
  "@id": Id1;
  [k: string]: unknown;
}
