/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Name = string;
export type Type = string[] | string | null;
export type Author = string | IdentifierValue | (string | IdentifierValue)[];
export type Id1 = string;
export type Description = string;
export type Version = string;
export type Associatedpublication = string[] | string | null;
export type Additionaldocumentation = string | null;
export type Contenturl = string[] | string | null;
export type Ispartof = IdentifierValue[] | null;
export type Usedbycomputation = IdentifierValue[] | null;
/**
 * MD5 checksum of the digital object content
 */
export type Md5 = string[] | string | null;
/**
 * Hash of the digital object content (if not MD5)
 */
export type Hash = string[] | string | null;
/**
 * SHA-256 checksum of the digital object content
 */
export type Sha256 = string[] | string | null;
export type Fairscapeversion = string;
export type ProvWasgeneratedby = (string | IdentifierValue)[] | null;
export type ProvWasderivedfrom = (string | IdentifierValue)[] | null;
export type ProvWasattributedto = (string | IdentifierValue)[] | null;
export type Additionaltype = string | null;
export type EviStepsummary = string;
export type EviCodeanalysis = CodeAnalysis[] | null;
export type Name1 = string | null;
export type Summary = string;
export type Keyfunctions = string[] | null;
export type Concerns = string[] | null;
export type EviInputsummaries = DatasetSummary[] | null;
export type Name2 = string | null;
export type Role = string | null;
export type Description1 = string | null;
export type EviOutputsummaries = DatasetSummary[] | null;
export type EviConcerns = string[] | null;
export type EviLlmmodel = string;
export type EviLlmtemperature = number | null;
export type Datecreated = string;
export type EviInterpreterversion = string | null;

/**
 * LLM-generated annotation of a single evi:Computation step.
 *
 * A DigitalObject (Document) that annotates an evi:Computation.
 * The original Computation stays in the graph in its original form;
 * this annotation points to it via evi:annotates.
 */
export interface AnnotatedComputation {
  "@id": Id;
  name: Name;
  "@type"?: Type;
  author: Author;
  description: Description;
  version?: Version;
  associatedPublication?: Associatedpublication;
  additionalDocumentation?: Additionaldocumentation;
  contentUrl?: Contenturl;
  isPartOf?: Ispartof;
  usedByComputation?: Usedbycomputation;
  md5?: Md5;
  hash?: Hash;
  sha256?: Sha256;
  fairscapeVersion?: Fairscapeversion;
  "prov:wasGeneratedBy"?: ProvWasgeneratedby;
  "prov:wasDerivedFrom"?: ProvWasderivedfrom;
  "prov:wasAttributedTo"?: ProvWasattributedto;
  additionalType?: Additionaltype;
  "evi:annotates": IdentifierValue;
  "evi:stepSummary": EviStepsummary;
  "evi:codeAnalysis"?: EviCodeanalysis;
  "evi:inputSummaries"?: EviInputsummaries;
  "evi:outputSummaries"?: EviOutputsummaries;
  "evi:concerns"?: EviConcerns;
  "evi:llmModel": EviLlmmodel;
  "evi:llmTemperature"?: EviLlmtemperature;
  dateCreated: Datecreated;
  "evi:interpreterVersion"?: EviInterpreterversion;
  [k: string]: unknown;
}
export interface IdentifierValue {
  "@id": Id1;
  [k: string]: unknown;
}
/**
 * Analysis of a software entity used in the computation.
 */
export interface CodeAnalysis {
  software: IdentifierValue;
  name?: Name1;
  summary: Summary;
  keyFunctions?: Keyfunctions;
  concerns?: Concerns;
  [k: string]: unknown;
}
/**
 * Summary of a dataset's role in the computation.
 */
export interface DatasetSummary {
  dataset: IdentifierValue;
  name?: Name2;
  role?: Role;
  description?: Description1;
  [k: string]: unknown;
}
