/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Type = string | null;
export type Name = string;
export type Identifier = IdentifierPropertyValue[] | null;
export type Type1 = string;
export type Value = string;
export type Name1 = string;
export type Id1 = string;
export type Usedby = IdentifierValue[] | null;
export type Description = string | null;
export type Ispartof = IdentifierValue[] | null;

/**
 * Pydantic model for the Schema.org BioChemEntity datatype
 *
 * This class can apply to Protiens, Genes, Chemical Entities, or Biological Samples
 */
export interface BioChemEntity {
  "@id": Id;
  "@type"?: Type;
  name: Name;
  identifier?: Identifier;
  associatedDisease?: IdentifierValue | null;
  usedBy?: Usedby;
  description?: Description;
  isPartOf?: Ispartof;
  [k: string]: unknown;
}
export interface IdentifierPropertyValue {
  "@type"?: Type1;
  value: Value;
  name: Name1;
  [k: string]: unknown;
}
export interface IdentifierValue {
  "@id": Id1;
  [k: string]: unknown;
}
