/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Name = string | null;
export type Summary = string;
export type Keyfunctions = string[] | null;
export type Concerns = string[] | null;

/**
 * Analysis of a software entity used in the computation.
 */
export interface CodeAnalysis {
  software: IdentifierValue;
  name?: Name;
  summary: Summary;
  keyFunctions?: Keyfunctions;
  concerns?: Concerns;
  [k: string]: unknown;
}
export interface IdentifierValue {
  "@id": Id;
  [k: string]: unknown;
}
