/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Name = string;
export type Metadatatype = string | null;
export type Additionaltype = string | null;
export type Runby = string;
export type Description = string;
export type Datecreated = string;
export type Associatedpublication = string | null;
export type Additionaldocumentation = string | null;
export type Command = string[] | string | null;
export type Usedsoftware = IdentifierValue[] | null;
export type Id1 = string;
export type Useddataset = IdentifierValue[] | null;
export type Generated = IdentifierValue[] | null;

export interface Computation {
  "@id": Id;
  name: Name;
  metadataType?: Metadatatype;
  additionalType?: Additionaltype;
  runBy: Runby;
  description: Description;
  dateCreated: Datecreated;
  associatedPublication?: Associatedpublication;
  additionalDocumentation?: Additionaldocumentation;
  command?: Command;
  usedSoftware?: Usedsoftware;
  usedDataset?: Useddataset;
  generated?: Generated;
  [k: string]: unknown;
}
export interface IdentifierValue {
  "@id": Id1;
  [k: string]: unknown;
}
