/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Name = string | null;
export type Role = string | null;
export type Description = string | null;

/**
 * Summary of a dataset's role in the computation.
 */
export interface DatasetSummary {
  dataset: IdentifierValue;
  name?: Name;
  role?: Role;
  description?: Description;
  [k: string]: unknown;
}
export interface IdentifierValue {
  "@id": Id;
  [k: string]: unknown;
}
