/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Name = string;
export type Type = string[] | string | null;
export type Author = string | IdentifierValue | (string | IdentifierValue)[];
export type Id1 = string;
export type Description = string;
export type Version = string;
export type Associatedpublication = string[] | string | null;
export type Additionaldocumentation = string | null;
export type Contenturl = string[] | string | null;
export type Ispartof = IdentifierValue[] | null;
export type Usedbycomputation = IdentifierValue[] | null;
/**
 * MD5 checksum of the digital object content
 */
export type Md5 = string[] | string | null;
/**
 * Hash of the digital object content (if not MD5)
 */
export type Hash = string[] | string | null;
/**
 * SHA-256 checksum of the digital object content
 */
export type Sha256 = string[] | string | null;
export type Fairscapeversion = string;
export type ProvWasgeneratedby = (string | IdentifierValue)[] | null;
export type ProvWasderivedfrom = (string | IdentifierValue)[] | null;
export type ProvWasattributedto = (string | IdentifierValue)[] | null;

/**
 * Base class for DigitalObject types (Dataset, Software, MLModel)
 */
export interface DigitalObject {
  "@id": Id;
  name: Name;
  "@type"?: Type;
  author: Author;
  description: Description;
  version?: Version;
  associatedPublication?: Associatedpublication;
  additionalDocumentation?: Additionaldocumentation;
  contentUrl?: Contenturl;
  isPartOf?: Ispartof;
  usedByComputation?: Usedbycomputation;
  md5?: Md5;
  hash?: Hash;
  sha256?: Sha256;
  fairscapeVersion?: Fairscapeversion;
  "prov:wasGeneratedBy"?: ProvWasgeneratedby;
  "prov:wasDerivedFrom"?: ProvWasderivedfrom;
  "prov:wasAttributedTo"?: ProvWasattributedto;
  [k: string]: unknown;
}
export interface IdentifierValue {
  "@id": Id1;
  [k: string]: unknown;
}
