/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Guid = string;
export type MetadataType = ClassType;
export type ClassType = "Dataset" | "Software" | "Computation" | "Annotation" | "Schema" | "EvidenceGraph" | "ROCrate";
export type Name = string;
export type Context = {
  [k: string]: string;
} | null;
export type Url = string | null;
export type Description = string;
export type License = string | null;
export type Keywords = string[];
export type Published = boolean;

export interface FairscapeEVIBaseModel {
  "@id": Guid;
  "@type": MetadataType;
  name: Name;
  "@context"?: Context;
  url?: Url;
  description: Description;
  license?: License;
  keywords?: Keywords;
  published?: Published;
  [k: string]: unknown;
}
