/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Guid = string;
export type MetadataType = ClassType;
export type ClassType = "Dataset" | "Software" | "Computation" | "Schema" | "EvidenceGraph" | "ROCrate";
export type Name = string;
export type Context = {
  [k: string]: string;
} | null;
export type Url = string | null;

/**
 * Refers to the Fairscape BaseModel inherited from Pydantic
 *
 * Args:
 *     BaseModel (Default Pydantic): Every instance of the Fairscape BaseModel must contain
 *     an id, a type, and a name
 */
export interface FairscapeBaseModel {
  "@id": Guid;
  "@type": MetadataType;
  name: Name;
  "@context"?: Context;
  url?: Url;
  [k: string]: unknown;
}
