/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Type = string | string[];
export type Ispartof = IdentifierValue[] | null;
export type Id1 = string;

/**
 * Generic Metadata Element of an ROCrate
 */
export interface GenericMetadataElem {
  "@id": Id;
  "@type": Type;
  isPartOf?: Ispartof;
  [k: string]: unknown;
}
export interface IdentifierValue {
  "@id": Id1;
  [k: string]: unknown;
}
