/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Guid = string;
export type MetadataType = ClassType;
export type ClassType = "Dataset" | "Software" | "Computation" | "Annotation" | "Schema" | "EvidenceGraph" | "ROCrate";
export type Name = string;

export interface Identifier {
  "@id": Guid;
  "@type": MetadataType;
  name: Name;
  [k: string]: unknown;
}
