/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Name = string;
export type Type = string | null;
export type Manufacturer = string;
export type Model = string;
export type Description = string;
export type Associatedpublication = string | null;
export type Additionaldocumentation = string | null;
export type Usedbyexperiment = IdentifierValue[] | null;
export type Id1 = string;
export type Contenturl = string | null;

export interface Instrument {
  "@id": Id;
  name: Name;
  "@type"?: Type;
  manufacturer: Manufacturer;
  model: Model;
  description: Description;
  associatedPublication?: Associatedpublication;
  additionalDocumentation?: Additionaldocumentation;
  usedByExperiment?: Usedbyexperiment;
  contentUrl?: Contenturl;
  [k: string]: unknown;
}
export interface IdentifierValue {
  "@id": Id1;
  [k: string]: unknown;
}
