/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Type = string;
export type Name = string;
export type Type1 = string;
export type Contacttype = string | null;
export type Email = string | null;
export type Telephone = string | null;
export type Type2 = string;
export type Streetaddress = string | null;
export type Addresslocality = string | null;
export type Addressregion = string | null;
export type Postalcode = string | null;
export type Addresscountry = string | null;

/**
 * Institutional Review Board with structured contact and address info.
 */
export interface IRB {
  "@type"?: Type;
  name: Name;
  contactPoint?: ContactPoint | null;
  address?: PostalAddress | null;
  [k: string]: unknown;
}
/**
 * Schema.org ContactPoint for structured contact information.
 */
export interface ContactPoint {
  "@type"?: Type1;
  contactType?: Contacttype;
  email?: Email;
  telephone?: Telephone;
  [k: string]: unknown;
}
/**
 * Schema.org PostalAddress for structured address information.
 */
export interface PostalAddress {
  "@type"?: Type2;
  streetAddress?: Streetaddress;
  addressLocality?: Addresslocality;
  addressRegion?: Addressregion;
  postalCode?: Postalcode;
  addressCountry?: Addresscountry;
  [k: string]: unknown;
}
