/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Type = string | null;
export type Name = string;
export type Identifier = IdentifierPropertyValue[] | null;
export type Type1 = string;
export type Value = string;
export type Name1 = string;
export type Drug = IdentifierValue[] | null;
export type Id1 = string;
export type Usedby = IdentifierValue[] | null;
export type Description = string;

/**
 * Pydantic model for the Schema.org MedicalCondition datatype
 *
 * This class represents any condition of the human body that affects the normal functioning of a person, whether physically or mentally. Includes diseases, injuries, disabilities, disorders, syndromes, etc.
 */
export interface MedicalCondition {
  "@id": Id;
  "@type"?: Type;
  name: Name;
  identifier?: Identifier;
  drug?: Drug;
  usedBy?: Usedby;
  description: Description;
  [k: string]: unknown;
}
export interface IdentifierPropertyValue {
  "@type"?: Type1;
  value: Value;
  name: Name1;
  [k: string]: unknown;
}
export interface IdentifierValue {
  "@id": Id1;
  [k: string]: unknown;
}
