/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Type = string | string[];
export type Name = string;
export type Description = string;
export type Author = string | string[];
export type Keywords = string[];
export type Version = string;
export type Modeltype = string | string[];
export type Framework = string | string[];
export type Modelformat = string | string[];
export type Trainingdataset = string | IdentifierValue[];
export type Id1 = string;
export type Parameters = number | null;
export type Inputsize = string | null;
export type Hasbias = string | null;
export type Intendedusecase = string | null;
export type Usageinformation = string | null;
export type Basemodel = string | null;
export type Associatedpublication = string[] | string | null;
export type Contenturl = string | string[];
export type Url = string | null;
export type License = string | null;
export type Citation = string | null;
export type Ispartof = IdentifierValue[] | null;

/**
 * Model Card for ML models as RO-Crate Dataset elements
 */
export interface ModelCard {
  "@id": Id;
  "@type"?: Type;
  name: Name;
  description: Description;
  author: Author;
  keywords: Keywords;
  version: Version;
  modelType: Modeltype;
  framework: Framework;
  modelFormat: Modelformat;
  trainingDataset: Trainingdataset;
  generatedBy: IdentifierValue;
  parameters?: Parameters;
  inputSize?: Inputsize;
  hasBias?: Hasbias;
  intendedUseCase?: Intendedusecase;
  usageInformation?: Usageinformation;
  baseModel?: Basemodel;
  associatedPublication?: Associatedpublication;
  contentUrl?: Contenturl;
  url?: Url;
  license?: License;
  citation?: Citation;
  isPartOf?: Ispartof;
  [k: string]: unknown;
}
export interface IdentifierValue {
  "@id": Id1;
  [k: string]: unknown;
}
