/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Name = string;
export type Type = string | null;
export type Sdpublisher = string;
export type Ispartof = IdentifierValue[] | null;
export type Id1 = string;
export type Diagnosis = IdentifierValue[] | null;
export type Drug = IdentifierValue[] | null;
export type Healthcondition = IdentifierValue[] | null;
export type Gender = string | null;
export type Birthdate = string | null;
export type Deathdate = string | null;
export type Fairscapeversion = string;

export interface Patient {
  "@id": Id;
  name: Name;
  "@type"?: Type;
  sdPublisher: Sdpublisher;
  isPartOf?: Ispartof;
  diagnosis?: Diagnosis;
  drug?: Drug;
  healthCondition?: Healthcondition;
  gender: Gender;
  birthDate?: Birthdate;
  deathDate?: Deathdate;
  fairscapeVersion?: Fairscapeversion;
  [k: string]: unknown;
}
export interface IdentifierValue {
  "@id": Id1;
  [k: string]: unknown;
}
