/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Type = string;
export type Streetaddress = string | null;
export type Addresslocality = string | null;
export type Addressregion = string | null;
export type Postalcode = string | null;
export type Addresscountry = string | null;

/**
 * Schema.org PostalAddress for structured address information.
 */
export interface PostalAddress {
  "@type"?: Type;
  streetAddress?: Streetaddress;
  addressLocality?: Addresslocality;
  addressRegion?: Addressregion;
  postalCode?: Postalcode;
  addressCountry?: Addresscountry;
  [k: string]: unknown;
}
