/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Type = "CreativeWork";
export type Id1 = string;

/**
 * Metadata Element of an ROCrate cooresponding to the `ro-crate-metadata.json` file itself
 *
 * Example
 *
 *     ```
 *     {
 *         "@id": "ro-crate-metadata.json",
 *         "@type": "CreativeWork",
 *         "conformsTo": {
 *             "@id": "https://w3id.org/ro/crate/1.2-DRAFT"
 *         },
 *         "about": {
 *             "@id": "https://fairscape.net/ark:59852/rocrate-2.cm4ai_chromatin_mda-mb-468_untreated_apmsembed_initialrun0.1alpha"
 *         }
 *     }
 *     ```
 */
export interface ROCrateMetadataFileElem {
  "@id": Id;
  "@type": Type;
  conformsTo: IdentifierValue;
  about: IdentifierValue;
  [k: string]: unknown;
}
export interface IdentifierValue {
  "@id": Id1;
  [k: string]: unknown;
}
