/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Type = string[];
export type Name = string;
export type Description = string;
export type Keywords = string[];
export type Ispartof = IdentifierValue[] | null;
export type Id1 = string;
export type Version = string;
export type Haspart = IdentifierValue[];
export type Author = string | string[];
export type License = string | null;
export type Associatedpublication = string[] | string | null;
export type Conditionsofaccess = string | null;
export type Copyrightnotice = string | null;
export type RaiDatalimitations = string | null;
export type RaiDatabiases = string | null;
export type RaiDatausecases = string | null;
export type RaiDatareleasemaintenanceplan = string | null;
export type RaiDatacollection = string | null;
export type RaiDatacollectiontype = string[] | null;
export type RaiDatacollectionmissingdata = string | null;
export type RaiDatacollectionrawdata = string | null;
export type RaiDatacollectiontimeframe = string[] | null;
export type RaiDataimputationprotocol = string | null;
export type RaiDatamanipulationprotocol = string | null;
export type RaiDatapreprocessingprotocol = string[] | null;
export type RaiDataannotationprotocol = string | null;
export type RaiDataannotationplatform = string[] | null;
export type RaiDataannotationanalysis = string[] | null;
export type RaiPersonalsensitiveinformation = string[] | null;
export type RaiDatasocialimpact = string | null;
export type RaiAnnotationsperitem = string | null;
export type RaiAnnotatordemographics = string[] | null;
export type RaiMachineannotationtools = string[] | null;

/**
 * Metadata Element of ROCrate that represents the crate as a whole
 *
 * Example
 *     ```
 *     {
 *         '@id': 'https://fairscape.net/ark:59852/rocrate-2.cm4ai_chromatin_mda-mb-468_untreated_imageembedfold1_initialrun0.1alpha',
 *         '@type': ['Dataset', 'https://w3id.org/EVI#ROCrate'],
 *         'name': 'Initial integration run',
 *         'description': 'Ideker Lab CM4AI 0.1 alpha MDA-MB-468 untreated chromatin Initial integration run IF Image Embedding IF microscopy images embedding fold1',
 *         'keywords': ['Ideker Lab', 'fold1'],
 *         'isPartOf': [
 *             {'@id': 'ark:/Ideker_Lab'},
 *             {'@id': 'ark:/Ideker_Lab/CM4AI'}
 *             ],
 *         'version': '0.5alpha',
 *         'license': 'https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en',
 *         'associatedPublication': 'Clark T, Schaffer L, Obernier K, Al Manir S, Churas CP, Dailamy A, Doctor Y, Forget A, Hansen JN, Hu M, Lenkiewicz J, Levinson MA, Marquez C, Mohan J, Nourreddine S, Niestroy J, Pratt D, Qian G, Thaker S, Belisle-Pipon J-C, Brandt C, Chen J, Ding Y, Fodeh S, Krogan N, Lundberg E, Mali P, Payne-Foster P, Ratcliffe S, Ravitsky V, Sali A, Schulz W, Ideker T. Cell Maps for Artificial Intelligence: AI-Ready Maps of Human Cell Architecture from Disease-Relevant Cell Lines. BioRXiv 2024.',
 *         'author': ['Test']
 *         'conditionsOfAccess': 'This dataset was created by investigators and staff of the Cell Maps for Artificial Intelligence project (CM4AI - https://cm4ai.org), a Data Generation Project of the NIH Bridge2AI program, and is copyright (c) 2024 by The Regents of the University of California and, for cellular imaging data, by The Board of Trustees of the Leland Stanford Junior University. It is licensed for reuse under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC-BY-NC-SA 4.0) license, whose terms are summarized here: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en.  Proper attribution credit as required by the license includes citation of the copyright holders and of the attribution parties, which includes citation of the following article: Clark T, Schaffer L, Obernier K, Al Manir S, Churas CP, Dailamy A, Doctor Y, Forget A, Hansen JN, Hu M, Lenkiewicz J, Levinson MA, Marquez C, Mohan J, Nourreddine S, Niestroy J, Pratt D, Qian G, Thaker S, Belisle-Pipon J-C, Brandt C, Chen J, Ding Y, Fodeh S, Krogan N, Lundberg E, Mali P, Payne-Foster P, Ratcliffe S, Ravitsky V, Sali A, Schulz W, Ideker T. Cell Maps for Artificial Intelligence: AI-Ready Maps of Human Cell Architecture from Disease-Relevant Cell Lines. BioRXiv 2024."',
 *         'copyrightNotice': 'Copyright (c) 2024 by The Regents of the University of California',
 *         'hasPart': [
 *             {'@id': 'https://fairscape.net/ark:59852/software-cellmaps_image_embedding-N2ux5jg'},
 *             {'@id': 'https://fairscape.net/ark:59852/dataset-cellmaps_image_embedding-output-file-N2ux5jg'},
 *             {'@id': 'https://fairscape.net/ark:59852/dataset-Densenet-model-file-N2ux5jg'},
 *             {'@id': 'https://fairscape.net/ark:59852/computation-IF-Image-Embedding-N2ux5jg'}
 *         ]
 *     }
 *     ```
 */
export interface ROCrateMetadataElem {
  "@id": Id;
  "@type": Type;
  name: Name;
  description: Description;
  keywords: Keywords;
  isPartOf?: Ispartof;
  version: Version;
  hasPart: Haspart;
  author: Author;
  license: License;
  associatedPublication?: Associatedpublication;
  conditionsOfAccess?: Conditionsofaccess;
  copyrightNotice?: Copyrightnotice;
  "rai:dataLimitations"?: RaiDatalimitations;
  "rai:dataBiases"?: RaiDatabiases;
  "rai:dataUseCases"?: RaiDatausecases;
  "rai:dataReleaseMaintenancePlan"?: RaiDatareleasemaintenanceplan;
  "rai:dataCollection"?: RaiDatacollection;
  "rai:dataCollectionType"?: RaiDatacollectiontype;
  "rai:dataCollectionMissingData"?: RaiDatacollectionmissingdata;
  "rai:dataCollectionRawData"?: RaiDatacollectionrawdata;
  "rai:dataCollectionTimeframe"?: RaiDatacollectiontimeframe;
  "rai:dataImputationProtocol"?: RaiDataimputationprotocol;
  "rai:dataManipulationProtocol"?: RaiDatamanipulationprotocol;
  "rai:dataPreprocessingProtocol"?: RaiDatapreprocessingprotocol;
  "rai:dataAnnotationProtocol"?: RaiDataannotationprotocol;
  "rai:dataAnnotationPlatform"?: RaiDataannotationplatform;
  "rai:dataAnnotationAnalysis"?: RaiDataannotationanalysis;
  "rai:personalSensitiveInformation"?: RaiPersonalsensitiveinformation;
  "rai:dataSocialImpact"?: RaiDatasocialimpact;
  "rai:annotationsPerItem"?: RaiAnnotationsperitem;
  "rai:annotatorDemographics"?: RaiAnnotatordemographics;
  "rai:machineAnnotationTools"?: RaiMachineannotationtools;
  [k: string]: unknown;
}
export interface IdentifierValue {
  "@id": Id1;
  [k: string]: unknown;
}
