/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Extractedrocratebucket = string | null;
export type Archivedrocratebucket = string | null;
export type Extractedobjectpath = string[] | null;
export type Archivedobjectpath = string | null;

export interface ROCrateDistribution {
  extractedROCrateBucket?: Extractedrocratebucket;
  archivedROCrateBucket?: Archivedrocratebucket;
  extractedObjectPath?: Extractedobjectpath;
  archivedObjectPath?: Archivedobjectpath;
  [k: string]: unknown;
}
