/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Context = {
  [k: string]: unknown;
} | null;
export type Id = string;
export type Name = string;
export type Type = string[] | string | null;
export type Author = string | IdentifierValue | (string | IdentifierValue)[];
export type Id1 = string;
export type Description = string;
export type Version = string;
export type Associatedpublication = string[] | string | null;
export type Additionaldocumentation = string | null;
export type Contenturl = string[] | string | null;
export type Ispartof = IdentifierValue[] | null;
export type Usedbycomputation = IdentifierValue[] | null;
/**
 * MD5 checksum of the digital object content
 */
export type Md5 = string[] | string | null;
/**
 * Hash of the digital object content (if not MD5)
 */
export type Hash = string[] | string | null;
/**
 * SHA-256 checksum of the digital object content
 */
export type Sha256 = string[] | string | null;
export type Fairscapeversion = string;
export type ProvWasgeneratedby = (string | IdentifierValue)[] | null;
export type ProvWasderivedfrom = (string | IdentifierValue)[] | null;
export type ProvWasattributedto = (string | IdentifierValue)[] | null;
export type Additionaltype = string | null;
export type Datepublished = string;
export type Keywords = string[];
export type Format = string;
export type Generatedby = IdentifierValue | IdentifierValue[] | null;
export type Derivedfrom = IdentifierValue[] | null;
export type Splits = Split[] | null;
export type Name1 = string;
export type Description1 = string | null;
/**
 * Croissant-aligned split type semantics.
 *
 * Maps to:
 *   cr:TrainingSplit   -> "train"
 *   cr:ValidationSplit -> "validation"
 *   cr:TestSplit       -> "test"
 *   custom             -> "other"
 */
export type SplitType = "train" | "validation" | "test" | "other";
export type Query = string | null;
export type Querytype = string | null;
export type Sourcedatasets = IdentifierValue[] | null;
export type Issample = boolean | null;
export type Israndom = boolean | null;
export type Samplingstrategy = string | null;
export type Id2 = string;
export type Name2 = string;
export type Type1 = string[] | string | null;
export type Author1 = string | IdentifierValue | (string | IdentifierValue)[];
export type Description2 = string;
export type Version1 = string;
export type Associatedpublication1 = string[] | string | null;
export type Additionaldocumentation1 = string | null;
export type Contenturl1 = string[] | string | null;
export type Ispartof1 = IdentifierValue[] | null;
export type Usedbycomputation1 = IdentifierValue[] | null;
/**
 * MD5 checksum of the digital object content
 */
export type Md51 = string[] | string | null;
/**
 * Hash of the digital object content (if not MD5)
 */
export type Hash1 = string[] | string | null;
/**
 * SHA-256 checksum of the digital object content
 */
export type Sha2561 = string[] | string | null;
export type Fairscapeversion1 = string;
export type ProvWasgeneratedby1 = (string | IdentifierValue)[] | null;
export type ProvWasderivedfrom1 = (string | IdentifierValue)[] | null;
export type ProvWasattributedto1 = (string | IdentifierValue)[] | null;
export type Additionaltype1 = string | null;
export type Datemodified = string | null;
export type FileFormat = string;
export type Id3 = string;
export type Name3 = string;
export type Type2 = string[] | string | null;
export type Author2 = string | IdentifierValue | (string | IdentifierValue)[];
export type Description3 = string;
export type Version2 = string;
export type Associatedpublication2 = string[] | string | null;
export type Additionaldocumentation2 = string | null;
export type Contenturl2 = string[] | string | null;
export type Ispartof2 = IdentifierValue[] | null;
export type Usedbycomputation2 = IdentifierValue[] | null;
/**
 * MD5 checksum of the digital object content
 */
export type Md52 = string[] | string | null;
/**
 * Hash of the digital object content (if not MD5)
 */
export type Hash2 = string[] | string | null;
/**
 * SHA-256 checksum of the digital object content
 */
export type Sha2562 = string[] | string | null;
export type Fairscapeversion2 = string;
export type ProvWasgeneratedby2 = (string | IdentifierValue)[] | null;
export type ProvWasderivedfrom2 = (string | IdentifierValue)[] | null;
export type ProvWasattributedto2 = (string | IdentifierValue)[] | null;
export type Additionaltype2 = string | null;
export type Datemodified1 = string | null;
export type Format1 = string;
export type Modeltask = string | null;
export type Modelarchitecture = string | null;
export type Trainedon = IdentifierValue[] | null;
export type Generatedby1 = IdentifierValue | IdentifierValue[] | null;
export type Derivedfrom1 = IdentifierValue[] | null;
export type Id4 = string;
export type Name4 = string;
export type Type3 = string[] | string | null;
export type Description4 = string;
export type Associatedpublication3 = string | null;
export type Generated = IdentifierValue[] | null;
export type Ispartof3 = IdentifierValue[] | null;
export type ProvUsed = (string | IdentifierValue)[] | null;
export type ProvWasassociatedwith = (string | IdentifierValue)[] | null;
export type Fairscapeversion3 = string;
export type Additionaltype3 = string | null;
export type Runby = string | IdentifierValue;
export type Datecreated = string;
export type Additionaldocumentation3 = string | null;
export type Command = string[] | string | null;
export type Usedsoftware = IdentifierValue[] | null;
export type Usedmlmodel = IdentifierValue[] | null;
export type Useddataset = IdentifierValue[] | null;
export type EviAnnotatedby = IdentifierValue[] | null;
export type Id5 = string;
export type Name5 = string;
export type Type4 = string | null;
export type Description5 = string;
export type Associatedpublication4 = string | null;
export type Generated1 = IdentifierValue[] | null;
export type Ispartof4 = IdentifierValue[] | null;
export type ProvUsed1 = (string | IdentifierValue)[] | null;
export type ProvWasassociatedwith1 = (string | IdentifierValue)[] | null;
export type Fairscapeversion4 = string;
export type Additionaltype4 = string | null;
export type Createdby = string | IdentifierValue;
export type Datecreated1 = string;
export type Useddataset1 = IdentifierValue[] | null;
export type Id6 = string;
export type Name6 = string;
export type Type5 = string[] | string | null;
export type Description6 = string;
export type Associatedpublication5 = string | null;
export type Generated2 = IdentifierValue[] | null;
export type Ispartof5 = IdentifierValue[] | null;
export type ProvUsed2 = (string | IdentifierValue)[] | null;
export type ProvWasassociatedwith2 = (string | IdentifierValue)[] | null;
export type Fairscapeversion5 = string;
export type Experimenttype = string;
export type Runby1 = string | IdentifierValue;
export type Dateperformed = string;
export type Protocol = string | null;
export type Usedinstrument = IdentifierValue[] | null;
export type Usedsample = IdentifierValue[] | null;
export type Usedtreatment = IdentifierValue[] | null;
export type Usedstain = IdentifierValue[] | null;
/**
 * Persistent unique identifier for this RO-Crate (ARK, DOI, URL, etc.).
 */
export type Id7 = string;
/**
 * RO-Crate type list; always includes 'Dataset' and 'https://w3id.org/EVI#ROCrate'. MUST NOT include 'Profile' — that type is reserved for the hand-authored Profile Crate at the profile URI.
 */
export type Type6 = string[];
/**
 * Profile this crate conforms to. Defaults to the Fairscape release profile URI.
 */
export type Conformsto = IdentifierValue | IdentifierValue[];
/**
 * A human-readable name for the dataset.
 */
export type Name7 = string;
/**
 * A human-readable description of the dataset.
 */
export type Description7 = string;
/**
 * Keywords or tags describing the dataset, used for discovery and search.
 */
export type Keywords1 = string[];
/**
 * Version string for this release of the dataset (e.g. '1.0', '2.3.1').
 */
export type Version3 = string;
/**
 * Date the dataset was published or made publicly available (ISO 8601).
 */
export type Datepublished1 = string | null;
/**
 * Parent organization(s) or project(s) this crate belongs to, referenced by identifier.
 */
export type Ispartof6 = IdentifierValue[] | null;
/**
 * Dataset, Software, Computation, and other entities that are part of this RO-Crate, referenced by identifier.
 */
export type Haspart = IdentifierValue[];
/**
 * Who created the dataset (e.g. which team, research group) and on behalf of which entity (e.g. company, institution, organization).
 */
export type Author3 = string | string[];
/**
 * Organization or person responsible for publishing or distributing the dataset.
 */
export type Publisher = string | null;
/**
 * A key individual (Principal Investigator) responsible for or overseeing dataset creation.
 */
export type Principalinvestigator = string | null;
/**
 * Who funded the creation of the dataset? Include grant names and numbers where applicable.
 */
export type Funder = string | null;
/**
 * Email address for questions or correspondence about the dataset.
 */
export type Contactemail = string | null;
/**
 * Preferred citation string for this dataset.
 */
export type Citation = string | null;
/**
 * Publication(s) associated with or describing this dataset.
 */
export type Associatedpublication6 = string[] | string | null;
/**
 * DOI or other external persistent identifier for the dataset (used for Findability and Sustainability scoring).
 */
export type Identifier = string | null;
/**
 * Will the dataset be distributed under a copyright or other IP license? Provide a link to or copy of the license terms (e.g. CC BY 4.0, MIT).
 */
export type License = string | null;
/**
 * Terms and conditions governing access to and use of this dataset, including any data use agreements required.
 */
export type Conditionsofaccess = string | null;
/**
 * Copyright statement for the dataset, including year and rights holder.
 */
export type Copyrightnotice = string | null;
/**
 * Total size of the dataset content (e.g. '2.4 GB', '150 MB'). Used in AI-Ready Characterization scoring.
 */
export type Contentsize = string | null;
/**
 * Additional usage information or instructions for working with this dataset.
 */
export type Usageinfo = string | null;
/**
 * Reference to a summary statistics entity describing distributions, counts, and key statistics for this dataset.
 */
export type Hassummarystatistics = string | IdentifierValue | null;
/**
 * Additional schema.org PropertyValue entries for metadata not covered by other fields (e.g. [{"name": "Human Subject", "value": "Yes"}]).
 */
export type Additionalproperty =
  | {
      [k: string]: unknown;
    }[]
  | null;
/**
 * Were any ethical or compliance review processes conducted (e.g. by an Institutional Review Board)? If so, describe the process, frequency of review, and outcomes. Or provide a contact for ethical review information.
 */
export type Ethicalreview = string | null;
/**
 * HL7 Confidentiality code indicating the level of confidentiality or sensitivity of the dataset (e.g. 'normal', 'restricted', 'very restricted').
 */
export type Confidentialitylevel = string | null;
/**
 * Institutional Review Board (IRB) information — approval status, approving institution, and contact details.
 */
export type Irb = string | IRB | null;
export type Type7 = string;
export type Name8 = string;
export type Type8 = string;
export type Contacttype = string | null;
export type Email = string | null;
export type Telephone = string | null;
export type Type9 = string;
export type Streetaddress = string | null;
export type Addresslocality = string | null;
export type Addressregion = string | null;
export type Postalcode = string | null;
export type Addresscountry = string | null;
/**
 * IRB protocol identifier number assigned by the reviewing institution.
 */
export type Irbprotocolid = string | null;
/**
 * If human subjects research qualifies for exemption from full IRB review, the applicable exemption category (e.g. 45 CFR 46 Exemption 4).
 */
export type Humansubjectexemption = string | null;
/**
 * Whether this dataset is subject to FDA regulations (e.g. clinical trial data, medical device data).
 */
export type Fdaregulated = boolean | null;
/**
 * Whether the dataset has been de-identified to remove or obscure personally identifiable information.
 */
export type Deidentified = boolean | null;
/**
 * Does this dataset involve human subjects? Indicate Yes/No and describe the nature of human subjects involvement.
 */
export type Humansubjectresearch = string | null;
/**
 * Name or contact for the data governance committee responsible for oversight, access control, and policy enforcement for this dataset.
 */
export type Datagovernancecommittee = string | null;
/**
 * MD5 checksum of the digital object content
 */
export type Md53 = string | null;
/**
 * Hash of the digital object content (if not MD5)
 */
export type Hash3 = string | null;
/**
 * SHA-256 checksum of the digital object content
 */
export type Sha2563 = string[] | string | null;
/**
 * Documents known limitations of the dataset that may affect its use or interpretation — data generalization limits (e.g. related to data distribution, data quality issues, or data sources) and non-recommended uses. Distinct from biases (systematic errors) and anomalies (data quality issues). (rai:dataLimitations)
 */
export type RaiDatalimitations = string[] | string | null;
/**
 * Documents known biases present in the dataset — systematic errors or prejudices that may affect the representativeness or fairness of the data. Distinct from anomalies (data quality issues) and limitations (scope constraints). (rai:dataBiases)
 */
export type RaiDatabiases = string[] | string | null;
/**
 * Explicit statement of intended uses for this dataset, focusing on positive, recommended applications. Recommended use categories: Training, Testing, Validation, Development or Production Use, Fine Tuning, others. Include usage guidelines and caveats. (rai:dataUseCases)
 */
export type RaiDatausecases = string[] | string | null;
/**
 * Will the dataset be updated (e.g. to correct labeling errors, add new instances, delete instances)? If so, how often, by whom, and how will updates be communicated? Covers versioning timeframe, maintainers, and deprecation policies. (rai:dataReleaseMaintenancePlan)
 */
export type RaiDatareleasemaintenanceplan = string[] | string | null;
/**
 * What mechanisms or procedures were used to collect the data (e.g. hardware sensors, manual curation, software APIs)? Also covers how these mechanisms were validated. (rai:dataCollection)
 */
export type RaiDatacollection = string | null;
/**
 * Data collection type(s). Recommended values: Surveys, Secondary Data Analysis, Physical Data Collection, Direct Measurement, Document Analysis, Manual Human Curator, Software Collection, Experiments, Web Scraping, Web API, Focus Groups, Self-Reporting, Customer Feedback Data, User-Generated Content Data, Passive Data Collection, Others. (rai:dataCollectionType)
 */
export type RaiDatacollectiontype = string[] | null;
/**
 * Documentation of missing data in the dataset, including patterns (e.g. MCAR, MAR, MNAR), known or suspected causes (e.g. sensor failures, participant dropout, privacy constraints), and strategies used to handle missing values. (rai:dataCollectionMissingData)
 */
export type RaiDatacollectionmissingdata = string | null;
/**
 * Description of raw data sources before preprocessing, cleaning, or labeling. Documents where the original data comes from and how it can be accessed. (rai:dataCollectionRawData)
 */
export type RaiDatacollectionrawdata = string | null;
/**
 * Over what timeframe was the data collected, and does this timeframe match the creation timeframe of the underlying data? Provide start and end dates where possible. (rai:dataCollectionTimeframe)
 */
export type RaiDatacollectiontimeframe = string[] | null;
/**
 * Description of data imputation methodology, including techniques used to handle missing values (e.g. mean/median imputation, forward fill, model-based imputation) and rationale for chosen approaches. (rai:dataImputationProtocol)
 */
export type RaiDataimputationprotocol = string | null;
/**
 * Was any cleaning of the data done (e.g. removal of instances, processing of missing values, deduplication, filtering)? If so, describe the cleaning procedures applied. (rai:dataManipulationProtocol)
 */
export type RaiDatamanipulationprotocol = string[] | string | null;
/**
 * Was any preprocessing of the data done (e.g. discretization or bucketing, tokenization, feature extraction, normalization)? Describe the steps required to bring collected data to a state that can be processed by an ML model or algorithm. (rai:dataPreprocessingProtocol)
 */
export type RaiDatapreprocessingprotocol = string[] | null;
/**
 * Annotation methodology, tasks, and protocols followed during labeling. Includes annotation guidelines, quality control procedures, task definitions, workforce type, annotation characteristics, and label distributions. (rai:dataAnnotationProtocol)
 */
export type RaiDataannotationprotocol = string | null;
/**
 * Platform or tool used for annotation (e.g. Label Studio, Prodigy, Amazon Mechanical Turk, custom annotation tool). (rai:dataAnnotationPlatform)
 */
export type RaiDataannotationplatform = string[] | null;
/**
 * Analysis of annotation quality, inter-annotator agreement metrics (e.g. Cohen's kappa, Fleiss' kappa), and systematic patterns in disagreements between annotators of different socio-demographic groups. Covers how final dataset labels relate to individual annotator responses. (rai:dataAnnotationAnalysis)
 */
export type RaiDataannotationanalysis = string[] | null;
/**
 * Does the dataset contain data that might be considered sensitive (e.g. race, sexual orientation, religion, biometrics)? List sensitive attribute types present: Gender, Socio-economic status, Geography, Language, Age, Culture, Experience or Seniority, others. (rai:personalSensitiveInformation)
 */
export type RaiPersonalsensitiveinformation = string[] | null;
/**
 * Is there anything about the dataset's composition or collection that might impact future uses or create risks/harm (e.g. unfair treatment, legal or financial risks)? Describe potential impacts and any mitigation strategies. (rai:dataSocialImpact)
 */
export type RaiDatasocialimpact = string | null;
/**
 * Number of annotations collected per data item. Multiple annotations per item enable calculation of inter-annotator agreement. (rai:annotationsPerItem)
 */
export type RaiAnnotationsperitem = string | null;
/**
 * Demographic information about annotators, if available and relevant (e.g. geographic location, language background, expertise level, age group, gender). (rai:annotatorDemographics)
 */
export type RaiAnnotatordemographics = string[] | null;
/**
 * Automated or machine-learning-based annotation tools used in dataset creation, including NLP pipelines, computer vision models, or other automated labeling systems. Format each entry as 'ToolName version' (e.g. 'spaCy 3.5.0'). (rai:machineAnnotationTools)
 */
export type RaiMachineannotationtools = string[] | null;
/**
 * Assessment of how complete the dataset is relative to its intended scope (e.g. percentage of expected records present, known gaps).
 */
export type Completeness = string | null;
/**
 * Explicit statement of prohibited or forbidden uses for this dataset — uses that are not permitted by license, ethics, or policy. Stronger than discouraged uses.
 */
export type Prohibiteduses = string | null;
/**
 * Pre-aggregated count of Dataset entities across all sub-crates. Used in AI-Ready Provenance scoring in place of counting entities at query time.
 */
export type EviDatasetcount = number | null;
/**
 * Pre-aggregated count of Computation and Experiment entities across all sub-crates. Used in AI-Ready Provenance scoring.
 */
export type EviComputationcount = number | null;
/**
 * Pre-aggregated count of Software entities across all sub-crates. Used in AI-Ready Provenance scoring.
 */
export type EviSoftwarecount = number | null;
/**
 * Pre-aggregated count of Schema entities across all sub-crates. Used in AI-Ready Characterization scoring.
 */
export type EviSchemacount = number | null;
/**
 * Pre-aggregated total content size in bytes across all sub-crate datasets. Used in AI-Ready Characterization scoring.
 */
export type EviTotalcontentsizebytes = number | null;
/**
 * Pre-aggregated count of entities that have hasSummaryStatistics set. Used in AI-Ready Characterization scoring.
 */
export type EviEntitieswithsummarystats = number | null;
/**
 * Pre-aggregated count of entities that have md5, sha256, or hash set. Used with evi:totalEntities to compute checksum coverage percentage.
 */
export type EviEntitieswithchecksums = number | null;
/**
 * Pre-aggregated total count of Dataset and Software entities. Used as denominator for checksum coverage in AI-Ready Pre-Model Explainability scoring.
 */
export type EviTotalentities = number | null;
/**
 * Pre-aggregated list of unique file format values (up to 5) across all entities. Used in AI-Ready Computability scoring.
 */
export type EviFormats = string[] | null;
/**
 * Flag indicating whether this release-level RO-Crate has been processed and aggregated metrics computed.
 */
export type EviProcessed = boolean | null;
/**
 * Was there a specific knowledge or resource gap that needed to be filled by creation of this dataset? (D4D_Motivation: AddressingGap)
 */
export type D4DAddressinggaps = string | null;
/**
 * Are there any errors, sources of noise, or redundancies in the dataset? (D4D_Composition: DataAnomaly)
 */
export type D4DDataanomalies = string | null;
/**
 * Does the dataset contain any data that might be offensive, insulting, threatening, or otherwise anxiety-provoking if viewed directly? (D4D_Composition: ContentWarning)
 */
export type D4DContentwarning = string | null;
/**
 * Details about informed consent procedures used in human subjects research — consent type, documentation, withdrawal mechanisms, and scope. (D4D_Human: InformedConsent)
 */
export type D4DInformedconsent = string | null;
/**
 * Information about protections for at-risk populations (e.g. children, pregnant women, prisoners, cognitively impaired individuals) included in human subjects research. (D4D_Human: AtRiskPopulations)
 */
export type D4DAtriskpopulations = string | null;
export type Id8 = string;
export type Type10 = "CreativeWork";
export type Fairscapeversion6 = string;
export type Guid = string;
export type Type11 = string;
export type Name9 = string;
export type Url = string | null;
export type Description8 = string;
export type License1 = string | null;
export type Keywords2 = string[];
export type Published = boolean;
export type Description9 = string;
export type Index = string | number;
export type Type12 = string;
export type ValueUrl = string | null;
export type Pattern = string | null;
export type MinItems = number | null;
export type MaxItems = number | null;
export type UniqueItems = boolean | null;
export type Properties1 = {
  [k: string]: Property;
} | null;
export type Type13 = string | null;
export type Additionalproperties = boolean | null;
export type Required = string[] | null;
export type Separator = string | null;
export type Header = boolean | null;
export type Examples =
  | {
      [k: string]: unknown;
    }[]
  | null;
export type Ispartof7 = IdentifierValue[] | null;
export type Fairscapeversion7 = string;
export type Id9 = string;
export type Type14 = string[] | string | null;
export type Name10 = string;
export type Identifier1 = IdentifierPropertyValue[] | null;
export type Type15 = string;
export type Value = string;
export type Name11 = string;
export type Usedby = IdentifierValue[] | null;
export type Description10 = string | null;
export type Ispartof8 = IdentifierValue[] | null;
export type Fairscapeversion8 = string;
export type Id10 = string;
export type Type16 = string | null;
export type Name12 = string;
export type Identifier2 = IdentifierPropertyValue[] | null;
export type Drug = IdentifierValue[] | null;
export type Usedby1 = IdentifierValue[] | null;
export type Ispartof9 = IdentifierValue[] | null;
export type Description11 = string;
export type Fairscapeversion9 = string;
export type Id11 = string;
export type Name13 = string;
export type Type17 = string | null;
export type Sdpublisher = string;
export type Ispartof10 = IdentifierValue[] | null;
export type Diagnosis = IdentifierValue[] | null;
export type Drug1 = IdentifierValue[] | null;
export type Healthcondition = IdentifierValue[] | null;
export type Gender = string | null;
export type Birthdate = string | null;
export type Deathdate = string | null;
export type Fairscapeversion10 = string;
export type Id12 = string;
export type Name14 = string;
export type Type18 = string[] | string | null;
export type Manufacturer = string;
export type Model = string;
export type Description12 = string;
export type Associatedpublication7 = string | null;
export type Additionaldocumentation4 = string | null;
export type Usedbyexperiment = IdentifierValue[] | null;
export type Contenturl3 = string | null;
export type Ispartof11 = IdentifierValue[] | null;
export type Fairscapeversion11 = string;
export type Id13 = string;
export type Name15 = string;
export type Type19 = string[] | string | null;
export type Author4 = string | string[];
export type Description13 = string;
export type Version4 = string;
export type Associatedpublication8 = string[] | string | null;
export type Additionaldocumentation5 = string | null;
export type Contenturl4 = string | string[];
export type Ispartof12 = IdentifierValue[] | null;
export type Usedbycomputation3 = IdentifierValue[] | null;
/**
 * MD5 checksum of the digital object content
 */
export type Md54 = string[] | string | null;
/**
 * Hash of the digital object content (if not MD5)
 */
export type Hash4 = string[] | string | null;
/**
 * SHA-256 checksum of the digital object content
 */
export type Sha2564 = string[] | string | null;
export type Fairscapeversion12 = string;
export type ProvWasgeneratedby3 = (string | IdentifierValue)[] | null;
export type ProvWasderivedfrom3 = (string | IdentifierValue)[] | null;
export type ProvWasattributedto3 = (string | IdentifierValue)[] | null;
export type Keywords3 = string[];
export type Modeltype = string[] | string | null;
export type Framework = string[] | string | null;
export type Modelformat = string[] | string | null;
export type Trainingdataset = string | IdentifierValue[] | null;
export type Derivedfrom2 = IdentifierValue[] | null;
export type Parameters = number | null;
export type Inputsize = string | null;
export type Hasbias = string | null;
export type Intendedusecase = string | null;
export type Usageinformation = string | null;
export type Basemodel = string | null;
export type Url1 = string | null;
export type License2 = string | null;
export type Citation1 = string | null;
export type Id14 = string;
export type Name16 = string;
export type Type20 = string[] | string | null;
export type Author5 = string | string[];
export type Description14 = string;
export type Keywords4 = string[];
export type Contenturl5 = string[] | string | null;
export type Ispartof13 = IdentifierValue[] | null;
export type Fairscapeversion13 = string;
export type Id15 = string;
export type Name17 = string;
export type Type21 = string[] | string | null;
export type Description15 = string;
export type Associatedpublication9 = string | null;
export type Generated3 = IdentifierValue[] | null;
export type Ispartof14 = IdentifierValue[] | null;
export type ProvUsed3 = (string | IdentifierValue)[] | null;
export type ProvWasassociatedwith3 = (string | IdentifierValue)[] | null;
export type Fairscapeversion14 = string;
export type Id16 = string;
export type Name18 = string;
export type Type22 = string[] | string | null;
export type Author6 = string | IdentifierValue | (string | IdentifierValue)[];
export type Description16 = string;
export type Version5 = string;
export type Associatedpublication10 = string[] | string | null;
export type Additionaldocumentation6 = string | null;
export type Contenturl6 = string[] | string | null;
export type Ispartof15 = IdentifierValue[] | null;
export type Usedbycomputation4 = IdentifierValue[] | null;
/**
 * MD5 checksum of the digital object content
 */
export type Md55 = string[] | string | null;
/**
 * Hash of the digital object content (if not MD5)
 */
export type Hash5 = string[] | string | null;
/**
 * SHA-256 checksum of the digital object content
 */
export type Sha2565 = string[] | string | null;
export type Fairscapeversion15 = string;
export type ProvWasgeneratedby4 = (string | IdentifierValue)[] | null;
export type ProvWasderivedfrom4 = (string | IdentifierValue)[] | null;
export type ProvWasattributedto4 = (string | IdentifierValue)[] | null;
export type Id17 = string;
export type Type23 = string | string[];
export type Ispartof16 = IdentifierValue[] | null;
export type Graph = (
  | Dataset
  | Software
  | MLModel
  | Computation
  | Annotation
  | Experiment
  | ROCrateMetadataElem
  | ROCrateMetadataFileElem
  | Schema
  | BioChemEntity
  | MedicalCondition
  | Patient
  | Instrument
  | ModelCard
  | Sample
  | Activity
  | DigitalObject
  | GenericMetadataElem
)[];

export interface ROCrateV1_2 {
  "@context"?: Context;
  "@graph": Graph;
  [k: string]: unknown;
}
export interface Dataset {
  "@id": Id;
  name: Name;
  "@type"?: Type;
  author: Author;
  description: Description;
  version?: Version;
  associatedPublication?: Associatedpublication;
  additionalDocumentation?: Additionaldocumentation;
  contentUrl?: Contenturl;
  isPartOf?: Ispartof;
  usedByComputation?: Usedbycomputation;
  md5?: Md5;
  hash?: Hash;
  sha256?: Sha256;
  fairscapeVersion?: Fairscapeversion;
  "prov:wasGeneratedBy"?: ProvWasgeneratedby;
  "prov:wasDerivedFrom"?: ProvWasderivedfrom;
  "prov:wasAttributedTo"?: ProvWasattributedto;
  additionalType?: Additionaltype;
  datePublished: Datepublished;
  keywords: Keywords;
  format: Format;
  "evi:Schema"?: IdentifierValue | null;
  generatedBy?: Generatedby;
  derivedFrom?: Derivedfrom;
  splits?: Splits;
  [k: string]: unknown;
}
export interface IdentifierValue {
  "@id": Id1;
  [k: string]: unknown;
}
/**
 * A named partition or subset of a Dataset.
 *
 * Unifies concepts from D4D DataSubset/SamplingStrategy and Croissant cr:Split.
 */
export interface Split {
  name: Name1;
  description?: Description1;
  splitType?: SplitType | null;
  query?: Query;
  queryType?: Querytype;
  sourceDatasets?: Sourcedatasets;
  isSample?: Issample;
  isRandom?: Israndom;
  samplingStrategy?: Samplingstrategy;
  [k: string]: unknown;
}
export interface Software {
  "@id": Id2;
  name: Name2;
  "@type"?: Type1;
  author: Author1;
  description: Description2;
  version?: Version1;
  associatedPublication?: Associatedpublication1;
  additionalDocumentation?: Additionaldocumentation1;
  contentUrl?: Contenturl1;
  isPartOf?: Ispartof1;
  usedByComputation?: Usedbycomputation1;
  md5?: Md51;
  hash?: Hash1;
  sha256?: Sha2561;
  fairscapeVersion?: Fairscapeversion1;
  "prov:wasGeneratedBy"?: ProvWasgeneratedby1;
  "prov:wasDerivedFrom"?: ProvWasderivedfrom1;
  "prov:wasAttributedTo"?: ProvWasattributedto1;
  additionalType?: Additionaltype1;
  dateModified?: Datemodified;
  format: FileFormat;
  [k: string]: unknown;
}
export interface MLModel {
  "@id": Id3;
  name: Name3;
  "@type"?: Type2;
  author: Author2;
  description: Description3;
  version?: Version2;
  associatedPublication?: Associatedpublication2;
  additionalDocumentation?: Additionaldocumentation2;
  contentUrl?: Contenturl2;
  isPartOf?: Ispartof2;
  usedByComputation?: Usedbycomputation2;
  md5?: Md52;
  hash?: Hash2;
  sha256?: Sha2562;
  fairscapeVersion?: Fairscapeversion2;
  "prov:wasGeneratedBy"?: ProvWasgeneratedby2;
  "prov:wasDerivedFrom"?: ProvWasderivedfrom2;
  "prov:wasAttributedTo"?: ProvWasattributedto2;
  additionalType?: Additionaltype2;
  dateModified?: Datemodified1;
  format: Format1;
  modelTask?: Modeltask;
  modelArchitecture?: Modelarchitecture;
  trainedOn?: Trainedon;
  generatedBy?: Generatedby1;
  derivedFrom?: Derivedfrom1;
  [k: string]: unknown;
}
export interface Computation {
  "@id": Id4;
  name: Name4;
  "@type"?: Type3;
  description: Description4;
  associatedPublication?: Associatedpublication3;
  generated?: Generated;
  isPartOf?: Ispartof3;
  "prov:used"?: ProvUsed;
  "prov:wasAssociatedWith"?: ProvWasassociatedwith;
  fairscapeVersion?: Fairscapeversion3;
  additionalType?: Additionaltype3;
  runBy: Runby;
  dateCreated: Datecreated;
  additionalDocumentation?: Additionaldocumentation3;
  command?: Command;
  usedSoftware?: Usedsoftware;
  usedMLModel?: Usedmlmodel;
  usedDataset?: Useddataset;
  "evi:annotatedBy"?: EviAnnotatedby;
  [k: string]: unknown;
}
export interface Annotation {
  "@id": Id5;
  name: Name5;
  "@type"?: Type4;
  description: Description5;
  associatedPublication?: Associatedpublication4;
  generated?: Generated1;
  isPartOf?: Ispartof4;
  "prov:used"?: ProvUsed1;
  "prov:wasAssociatedWith"?: ProvWasassociatedwith1;
  fairscapeVersion?: Fairscapeversion4;
  additionalType?: Additionaltype4;
  createdBy: Createdby;
  dateCreated: Datecreated1;
  usedDataset?: Useddataset1;
  [k: string]: unknown;
}
export interface Experiment {
  "@id": Id6;
  name: Name6;
  "@type"?: Type5;
  description: Description6;
  associatedPublication?: Associatedpublication5;
  generated?: Generated2;
  isPartOf?: Ispartof5;
  "prov:used"?: ProvUsed2;
  "prov:wasAssociatedWith"?: ProvWasassociatedwith2;
  fairscapeVersion?: Fairscapeversion5;
  experimentType: Experimenttype;
  runBy: Runby1;
  datePerformed: Dateperformed;
  protocol?: Protocol;
  usedInstrument?: Usedinstrument;
  usedSample?: Usedsample;
  usedTreatment?: Usedtreatment;
  usedStain?: Usedstain;
  [k: string]: unknown;
}
/**
 * Metadata Element of ROCrate that represents the crate as a whole
 *
 * Example
 *     ```
 *     {
 *         '@id': 'https://fairscape.net/ark:59852/rocrate-2.cm4ai_chromatin_mda-mb-468_untreated_imageembedfold1_initialrun0.1alpha',
 *         '@type': ['Dataset', 'https://w3id.org/EVI#ROCrate'],
 *         'conformsTo': {'@id': 'https://w3id.org/fairscape/profile/0.1'},
 *         'name': 'Initial integration run',
 *         'description': 'Ideker Lab CM4AI 0.1 alpha MDA-MB-468 untreated chromatin Initial integration run IF Image Embedding IF microscopy images embedding fold1',
 *         'keywords': ['Ideker Lab', 'fold1'],
 *         'isPartOf': [
 *             {'@id': 'ark:/Ideker_Lab'},
 *             {'@id': 'ark:/Ideker_Lab/CM4AI'}
 *             ],
 *         'version': '0.5alpha',
 *         'license': 'https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en',
 *         'associatedPublication': 'Clark T, Schaffer L, Obernier K, Al Manir S, Churas CP, Dailamy A, Doctor Y, Forget A, Hansen JN, Hu M, Lenkiewicz J, Levinson MA, Marquez C, Mohan J, Nourreddine S, Niestroy J, Pratt D, Qian G, Thaker S, Belisle-Pipon J-C, Brandt C, Chen J, Ding Y, Fodeh S, Krogan N, Lundberg E, Mali P, Payne-Foster P, Ratcliffe S, Ravitsky V, Sali A, Schulz W, Ideker T. Cell Maps for Artificial Intelligence: AI-Ready Maps of Human Cell Architecture from Disease-Relevant Cell Lines. BioRXiv 2024.',
 *         'author': ['Test']
 *         'conditionsOfAccess': 'This dataset was created by investigators and staff of the Cell Maps for Artificial Intelligence project (CM4AI - https://cm4ai.org), a Data Generation Project of the NIH Bridge2AI program, and is copyright (c) 2024 by The Regents of the University of California and, for cellular imaging data, by The Board of Trustees of the Leland Stanford Junior University. It is licensed for reuse under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC-BY-NC-SA 4.0) license, whose terms are summarized here: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en.  Proper attribution credit as required by the license includes citation of the copyright holders and of the attribution parties, which includes citation of the following article: Clark T, Schaffer L, Obernier K, Al Manir S, Churas CP, Dailamy A, Doctor Y, Forget A, Hansen JN, Hu M, Lenkiewicz J, Levinson MA, Marquez C, Mohan J, Nourreddine S, Niestroy J, Pratt D, Qian G, Thaker S, Belisle-Pipon J-C, Brandt C, Chen J, Ding Y, Fodeh S, Krogan N, Lundberg E, Mali P, Payne-Foster P, Ratcliffe S, Ravitsky V, Sali A, Schulz W, Ideker T. Cell Maps for Artificial Intelligence: AI-Ready Maps of Human Cell Architecture from Disease-Relevant Cell Lines. BioRXiv 2024."',
 *         'copyrightNotice': 'Copyright (c) 2024 by The Regents of the University of California',
 *         'hasPart': [
 *             {'@id': 'https://fairscape.net/ark:59852/software-cellmaps_image_embedding-N2ux5jg'},
 *             {'@id': 'https://fairscape.net/ark:59852/dataset-cellmaps_image_embedding-output-file-N2ux5jg'},
 *             {'@id': 'https://fairscape.net/ark:59852/dataset-Densenet-model-file-N2ux5jg'},
 *             {'@id': 'https://fairscape.net/ark:59852/computation-IF-Image-Embedding-N2ux5jg'}
 *         ]
 *     }
 *     ```
 */
export interface ROCrateMetadataElem {
  "@id": Id7;
  "@type": Type6;
  conformsTo?: Conformsto;
  name: Name7;
  description: Description7;
  keywords: Keywords1;
  version: Version3;
  datePublished?: Datepublished1;
  isPartOf?: Ispartof6;
  hasPart: Haspart;
  author: Author3;
  publisher?: Publisher;
  principalInvestigator?: Principalinvestigator;
  funder?: Funder;
  contactEmail?: Contactemail;
  citation?: Citation;
  associatedPublication?: Associatedpublication6;
  identifier?: Identifier;
  license: License;
  conditionsOfAccess?: Conditionsofaccess;
  copyrightNotice?: Copyrightnotice;
  contentSize?: Contentsize;
  usageInfo?: Usageinfo;
  hasSummaryStatistics?: Hassummarystatistics;
  additionalProperty?: Additionalproperty;
  ethicalReview?: Ethicalreview;
  confidentialityLevel?: Confidentialitylevel;
  irb?: Irb;
  irbProtocolId?: Irbprotocolid;
  humanSubjectExemption?: Humansubjectexemption;
  fdaRegulated?: Fdaregulated;
  deidentified?: Deidentified;
  humanSubjectResearch?: Humansubjectresearch;
  dataGovernanceCommittee?: Datagovernancecommittee;
  md5?: Md53;
  hash?: Hash3;
  sha256?: Sha2563;
  "rai:dataLimitations"?: RaiDatalimitations;
  "rai:dataBiases"?: RaiDatabiases;
  "rai:dataUseCases"?: RaiDatausecases;
  "rai:dataReleaseMaintenancePlan"?: RaiDatareleasemaintenanceplan;
  "rai:dataCollection"?: RaiDatacollection;
  "rai:dataCollectionType"?: RaiDatacollectiontype;
  "rai:dataCollectionMissingData"?: RaiDatacollectionmissingdata;
  "rai:dataCollectionRawData"?: RaiDatacollectionrawdata;
  "rai:dataCollectionTimeframe"?: RaiDatacollectiontimeframe;
  "rai:dataImputationProtocol"?: RaiDataimputationprotocol;
  "rai:dataManipulationProtocol"?: RaiDatamanipulationprotocol;
  "rai:dataPreprocessingProtocol"?: RaiDatapreprocessingprotocol;
  "rai:dataAnnotationProtocol"?: RaiDataannotationprotocol;
  "rai:dataAnnotationPlatform"?: RaiDataannotationplatform;
  "rai:dataAnnotationAnalysis"?: RaiDataannotationanalysis;
  "rai:personalSensitiveInformation"?: RaiPersonalsensitiveinformation;
  "rai:dataSocialImpact"?: RaiDatasocialimpact;
  "rai:annotationsPerItem"?: RaiAnnotationsperitem;
  "rai:annotatorDemographics"?: RaiAnnotatordemographics;
  "rai:machineAnnotationTools"?: RaiMachineannotationtools;
  completeness?: Completeness;
  prohibitedUses?: Prohibiteduses;
  "evi:datasetCount"?: EviDatasetcount;
  "evi:computationCount"?: EviComputationcount;
  "evi:softwareCount"?: EviSoftwarecount;
  "evi:schemaCount"?: EviSchemacount;
  "evi:totalContentSizeBytes"?: EviTotalcontentsizebytes;
  "evi:entitiesWithSummaryStats"?: EviEntitieswithsummarystats;
  "evi:entitiesWithChecksums"?: EviEntitieswithchecksums;
  "evi:totalEntities"?: EviTotalentities;
  "evi:formats"?: EviFormats;
  "evi:processed"?: EviProcessed;
  "d4d:addressingGaps"?: D4DAddressinggaps;
  "d4d:dataAnomalies"?: D4DDataanomalies;
  "d4d:contentWarning"?: D4DContentwarning;
  "d4d:informedConsent"?: D4DInformedconsent;
  "d4d:atRiskPopulations"?: D4DAtriskpopulations;
  [k: string]: unknown;
}
/**
 * Institutional Review Board with structured contact and address info.
 */
export interface IRB {
  "@type"?: Type7;
  name: Name8;
  contactPoint?: ContactPoint | null;
  address?: PostalAddress | null;
  [k: string]: unknown;
}
/**
 * Schema.org ContactPoint for structured contact information.
 */
export interface ContactPoint {
  "@type"?: Type8;
  contactType?: Contacttype;
  email?: Email;
  telephone?: Telephone;
  [k: string]: unknown;
}
/**
 * Schema.org PostalAddress for structured address information.
 */
export interface PostalAddress {
  "@type"?: Type9;
  streetAddress?: Streetaddress;
  addressLocality?: Addresslocality;
  addressRegion?: Addressregion;
  postalCode?: Postalcode;
  addressCountry?: Addresscountry;
  [k: string]: unknown;
}
/**
 * Metadata Element of an ROCrate cooresponding to the `ro-crate-metadata.json` file itself
 *
 * Example
 *
 *     ```
 *     {
 *         "@id": "ro-crate-metadata.json",
 *         "@type": "CreativeWork",
 *         "conformsTo": {
 *             "@id": "https://w3id.org/ro/crate/1.2"
 *         },
 *         "about": {
 *             "@id": "https://fairscape.net/ark:59852/rocrate-2.cm4ai_chromatin_mda-mb-468_untreated_apmsembed_initialrun0.1alpha"
 *         }
 *     }
 *     ```
 */
export interface ROCrateMetadataFileElem {
  "@id": Id8;
  "@type": Type10;
  conformsTo: IdentifierValue;
  about: IdentifierValue;
  fairscapeVersion?: Fairscapeversion6;
  [k: string]: unknown;
}
export interface Schema {
  "@id": Guid;
  "@type"?: Type11;
  name: Name9;
  "@context"?: Context1;
  url?: Url;
  description: Description8;
  license?: License1;
  keywords?: Keywords2;
  published?: Published;
  properties: Properties;
  type?: Type13;
  additionalProperties?: Additionalproperties;
  required?: Required;
  separator?: Separator;
  header?: Header;
  examples?: Examples;
  isPartOf?: Ispartof7;
  fairscapeVersion?: Fairscapeversion7;
  [k: string]: unknown;
}
export interface Context1 {
  [k: string]: string;
}
export interface Properties {
  [k: string]: Property;
}
export interface Property {
  description: Description9;
  index: Index;
  type: Type12;
  "value-url"?: ValueUrl;
  pattern?: Pattern;
  "min-items"?: MinItems;
  "max-items"?: MaxItems;
  "unique-items"?: UniqueItems;
  properties?: Properties1;
  [k: string]: unknown;
}
/**
 * Pydantic model for the Schema.org BioChemEntity datatype
 *
 * This class can apply to Protiens, Genes, Chemical Entities, or Biological Samples
 */
export interface BioChemEntity {
  "@id": Id9;
  "@type"?: Type14;
  name: Name10;
  identifier?: Identifier1;
  associatedDisease?: IdentifierValue | null;
  usedBy?: Usedby;
  description?: Description10;
  isPartOf?: Ispartof8;
  fairscapeVersion?: Fairscapeversion8;
  [k: string]: unknown;
}
export interface IdentifierPropertyValue {
  "@type"?: Type15;
  value: Value;
  name: Name11;
  [k: string]: unknown;
}
/**
 * Pydantic model for the Schema.org MedicalCondition datatype
 *
 * This class represents any condition of the human body that affects the normal functioning of a person, whether physically or mentally. Includes diseases, injuries, disabilities, disorders, syndromes, etc.
 */
export interface MedicalCondition {
  "@id": Id10;
  "@type"?: Type16;
  name: Name12;
  identifier?: Identifier2;
  drug?: Drug;
  usedBy?: Usedby1;
  isPartOf?: Ispartof9;
  description: Description11;
  fairscapeVersion?: Fairscapeversion9;
  [k: string]: unknown;
}
export interface Patient {
  "@id": Id11;
  name: Name13;
  "@type"?: Type17;
  sdPublisher: Sdpublisher;
  isPartOf?: Ispartof10;
  diagnosis?: Diagnosis;
  drug?: Drug1;
  healthCondition?: Healthcondition;
  gender: Gender;
  birthDate?: Birthdate;
  deathDate?: Deathdate;
  fairscapeVersion?: Fairscapeversion10;
  [k: string]: unknown;
}
export interface Instrument {
  "@id": Id12;
  name: Name14;
  "@type"?: Type18;
  manufacturer: Manufacturer;
  model: Model;
  description: Description12;
  associatedPublication?: Associatedpublication7;
  additionalDocumentation?: Additionaldocumentation4;
  usedByExperiment?: Usedbyexperiment;
  contentUrl?: Contenturl3;
  isPartOf?: Ispartof11;
  fairscapeVersion?: Fairscapeversion11;
  [k: string]: unknown;
}
/**
 * Model Card for ML models as RO-Crate Dataset elements
 */
export interface ModelCard {
  "@id": Id13;
  name: Name15;
  "@type"?: Type19;
  author: Author4;
  description: Description13;
  version: Version4;
  associatedPublication?: Associatedpublication8;
  additionalDocumentation?: Additionaldocumentation5;
  contentUrl?: Contenturl4;
  isPartOf?: Ispartof12;
  usedByComputation?: Usedbycomputation3;
  md5?: Md54;
  hash?: Hash4;
  sha256?: Sha2564;
  fairscapeVersion?: Fairscapeversion12;
  "prov:wasGeneratedBy"?: ProvWasgeneratedby3;
  "prov:wasDerivedFrom"?: ProvWasderivedfrom3;
  "prov:wasAttributedTo"?: ProvWasattributedto3;
  keywords: Keywords3;
  modelType?: Modeltype;
  framework?: Framework;
  modelFormat?: Modelformat;
  trainingDataset?: Trainingdataset;
  generatedBy?: IdentifierValue | null;
  derivedFrom?: Derivedfrom2;
  parameters?: Parameters;
  inputSize?: Inputsize;
  hasBias?: Hasbias;
  intendedUseCase?: Intendedusecase;
  usageInformation?: Usageinformation;
  baseModel?: Basemodel;
  url?: Url1;
  license?: License2;
  citation?: Citation1;
  [k: string]: unknown;
}
export interface Sample {
  "@id": Id14;
  name: Name16;
  "@type"?: Type20;
  author: Author5;
  description: Description14;
  keywords: Keywords4;
  contentUrl?: Contenturl5;
  cellLineReference?: IdentifierValue | null;
  isPartOf?: Ispartof13;
  fairscapeVersion?: Fairscapeversion13;
  [k: string]: unknown;
}
/**
 * Base class for Activity types (Computation, Annotation, Experiment)
 */
export interface Activity {
  "@id": Id15;
  name: Name17;
  "@type"?: Type21;
  description: Description15;
  associatedPublication?: Associatedpublication9;
  generated?: Generated3;
  isPartOf?: Ispartof14;
  "prov:used"?: ProvUsed3;
  "prov:wasAssociatedWith"?: ProvWasassociatedwith3;
  fairscapeVersion?: Fairscapeversion14;
  [k: string]: unknown;
}
/**
 * Base class for DigitalObject types (Dataset, Software, MLModel)
 */
export interface DigitalObject {
  "@id": Id16;
  name: Name18;
  "@type"?: Type22;
  author: Author6;
  description: Description16;
  version?: Version5;
  associatedPublication?: Associatedpublication10;
  additionalDocumentation?: Additionaldocumentation6;
  contentUrl?: Contenturl6;
  isPartOf?: Ispartof15;
  usedByComputation?: Usedbycomputation4;
  md5?: Md55;
  hash?: Hash5;
  sha256?: Sha2565;
  fairscapeVersion?: Fairscapeversion15;
  "prov:wasGeneratedBy"?: ProvWasgeneratedby4;
  "prov:wasDerivedFrom"?: ProvWasderivedfrom4;
  "prov:wasAttributedTo"?: ProvWasattributedto4;
  [k: string]: unknown;
}
/**
 * Generic Metadata Element of an ROCrate
 */
export interface GenericMetadataElem {
  "@id": Id17;
  "@type": Type23;
  isPartOf?: Ispartof16;
  [k: string]: unknown;
}
