/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Name = string;
export type Type = string | null;
export type Author = string | string[];
export type Description = string;
export type Keywords = string[];
export type Contenturl = string[] | string | null;
export type Id1 = string;
export type Ispartof = IdentifierValue[] | null;

export interface Sample {
  "@id": Id;
  name: Name;
  "@type"?: Type;
  author: Author;
  description: Description;
  keywords: Keywords;
  contentUrl?: Contenturl;
  cellLineReference?: IdentifierValue | null;
  isPartOf?: Ispartof;
  [k: string]: unknown;
}
export interface IdentifierValue {
  "@id": Id1;
  [k: string]: unknown;
}
