/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Guid = string;
export type Type = string;
export type Name = string;
export type Url = string | null;
export type Description = string;
export type License = string | null;
export type Keywords = string[];
export type Published = boolean;
export type Description1 = string;
export type Index = string | number;
export type Type1 = string;
export type ValueUrl = string | null;
export type Pattern = string | null;
export type Type2 = string;
export type MinItems = number | null;
export type MaxItems = number | null;
export type UniqueItems = boolean | null;
export type Type3 = string | null;
export type Additionalproperties = boolean | null;
export type Required = string[] | null;
export type Separator = string | null;
export type Header = boolean | null;
export type Examples =
  | {
      [k: string]: unknown;
    }[]
  | null;

export interface Schema {
  "@id": Guid;
  "@type"?: Type;
  name: Name;
  "@context"?: Context;
  url?: Url;
  description: Description;
  license?: License;
  keywords?: Keywords;
  published?: Published;
  properties: Properties;
  type?: Type3;
  additionalProperties?: Additionalproperties;
  required?: Required;
  separator?: Separator;
  header?: Header;
  examples?: Examples;
  [k: string]: unknown;
}
export interface Context {
  [k: string]: string;
}
export interface Properties {
  [k: string]: Property;
}
export interface Property {
  description: Description1;
  index: Index;
  type: Type1;
  "value-url"?: ValueUrl;
  pattern?: Pattern;
  items?: Item | null;
  "min-items"?: MinItems;
  "max-items"?: MaxItems;
  "unique-items"?: UniqueItems;
  [k: string]: unknown;
}
export interface Item {
  type: Type2;
  [k: string]: unknown;
}
