/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Name = string;
export type Metadatatype = string | null;
export type Additionaltype = string | null;
export type Author = string;
export type Datemodified = string;
export type Version = string;
export type Description = string;
export type Associatedpublication = string | null;
export type Additionaldocumentation = string | null;
export type FileFormat = string;
export type Usedbycomputation = IdentifierValue[] | null;
export type Id1 = string;
export type Contenturl = string | null;

export interface Software {
  "@id": Id;
  name: Name;
  metadataType?: Metadatatype;
  additionalType?: Additionaltype;
  author: Author;
  dateModified: Datemodified;
  version?: Version;
  description: Description;
  associatedPublication?: Associatedpublication;
  additionalDocumentation?: Additionaldocumentation;
  format: FileFormat;
  usedByComputation?: Usedbycomputation;
  contentUrl?: Contenturl;
  [k: string]: unknown;
}
export interface IdentifierValue {
  "@id": Id1;
  [k: string]: unknown;
}
