/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type Description = string | null;
/**
 * Croissant-aligned split type semantics.
 *
 * Maps to:
 *   cr:TrainingSplit   -> "train"
 *   cr:ValidationSplit -> "validation"
 *   cr:TestSplit       -> "test"
 *   custom             -> "other"
 */
export type SplitType = "train" | "validation" | "test" | "other";
export type Query = string | null;
export type Querytype = string | null;
export type Sourcedatasets = IdentifierValue[] | null;
export type Id = string;
export type Issample = boolean | null;
export type Israndom = boolean | null;
export type Samplingstrategy = string | null;

/**
 * A named partition or subset of a Dataset.
 *
 * Unifies concepts from D4D DataSubset/SamplingStrategy and Croissant cr:Split.
 */
export interface Split {
  name: Name;
  description?: Description;
  splitType?: SplitType | null;
  query?: Query;
  queryType?: Querytype;
  sourceDatasets?: Sourcedatasets;
  isSample?: Issample;
  isRandom?: Israndom;
  samplingStrategy?: Samplingstrategy;
  [k: string]: unknown;
}
export interface IdentifierValue {
  "@id": Id;
  [k: string]: unknown;
}
